app.settings:
  indentJson: true
  rabbit:
    host: 192.168.99.100
    port: 5672
    user: test
    pass: qwerty

    exchange: chat.E.fanout.dev.Message
    queue: chat.Q.dev.MessageSubscriber.Message

    maxConnections: 10
    maxConcurrentConsumers: 5

logging:
  level:
    org.springframework.amqp.rabbit.core.RabbitTemplate: INFO
    com.mintbeans.chat.service:
      MessagePublisher: INFO
      MessageSubscriber: DEBUG